# Generated by Django 4.2.13 on 2024-08-18 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleTitle', models.CharField(blank=True, max_length=30, null=True)),
                ('articleDescription', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleUsersApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(blank=True, max_length=30, null=True)),
                ('companyName', models.CharField(blank=True, max_length=30, null=True)),
                ('courseDescription', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseUsersApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyPicture', models.FileField(blank=True, null=True, upload_to='images/')),
                ('jobTitle', models.CharField(blank=True, max_length=30, null=True)),
                ('companyName', models.CharField(blank=True, max_length=30, null=True)),
                ('jobSalary', models.CharField(blank=True, max_length=30, null=True)),
                ('jobDescription', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(blank=True, max_length=30, null=True)),
                ('companyName', models.CharField(blank=True, max_length=30, null=True)),
                ('userName', models.CharField(blank=True, max_length=30, null=True)),
                ('realName', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('jobApplied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributor.job')),
            ],
        ),
    ]
