# Generated by Django 4.2.13 on 2024-08-18 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contributor', '0001_initial'),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationdetails',
            name='userApplied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.normaluser'),
        ),
        migrations.AddField(
            model_name='job',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.contributor'),
        ),
        migrations.AddField(
            model_name='courseusersapplied',
            name='courseApplied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributor.course'),
        ),
        migrations.AddField(
            model_name='courseusersapplied',
            name='userApplied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.normaluser'),
        ),
        migrations.AddField(
            model_name='course',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.contributor'),
        ),
        migrations.AddField(
            model_name='articleusersapplied',
            name='articleApplied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributor.article'),
        ),
        migrations.AddField(
            model_name='articleusersapplied',
            name='userApplied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.normaluser'),
        ),
        migrations.AddField(
            model_name='article',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.contributor'),
        ),
    ]
