# Generated by Django 4.2.13 on 2024-08-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('contributor', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplicationdetails',
            unique_together={('userApplied', 'jobApplied')},
        ),
    ]
