# Generated by Django 4.2.13 on 2024-08-19 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('contributor', '0003_alter_jobapplicationdetails_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(blank=True, max_length=30, null=True)),
                ('companyName', models.CharField(blank=True, max_length=30, null=True)),
                ('userName', models.CharField(blank=True, max_length=30, null=True)),
                ('realName', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.IntegerField()),
                ('startDate', models.CharField(blank=True, max_length=30, null=True)),
                ('courseApplied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributor.course')),
                ('userApplied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.normaluser')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseusersapplied',
            name='courseApplied',
        ),
        migrations.RemoveField(
            model_name='courseusersapplied',
            name='userApplied',
        ),
        migrations.DeleteModel(
            name='ArticleUsersApplied',
        ),
        migrations.DeleteModel(
            name='CourseUsersApplied',
        ),
    ]
