# Generated by Django 4.2.13 on 2024-08-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('contributor', '0004_courseapplicationdetails_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseapplicationdetails',
            unique_together={('userApplied', 'courseApplied')},
        ),
    ]
